services:

  orders_db:
    image: postgres:17.5-alpine
    hostname: orders_db
    ports:
      - "54321:5432"
    networks:
      - orders_system
    environment:
      POSTGRES_USER: "${ORDERS_DB_USERNAME}"
      POSTGRES_PASSWORD: "${ORDERS_DB_PASSWORD}"
      POSTGRES_DB: orders

  kafka:
    image: apache/kafka:4.1.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      - orders_system
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:v1.4.2
    container_name: kafka_ui
    ports:
      - "8083:8080"
    networks:
      - orders_system
    environment:
      KAFKA_CLUSTERS_0_NAME: local-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      DYNAMIC_CONFIG_ENABLED: 'true'

  orders_service:
    image: snds_prfct/orders-service:0.1
    build: orders-service/
    container_name: orders_service
    depends_on:
      - orders_db
      - kafka
    ports:
      - "8080:8080"
    networks:
      - orders_system
    environment:
      DATABASE_BASE_URL: jdbc:postgresql://orders_db
      DATABASE_NAME: orders
      DATABASE_USERNAME: "${ORDERS_DB_USERNAME}"
      DATABASE_PASSWORD: "${ORDERS_DB_PASSWORD}"
      FLYWAY_USER: "${ORDERS_DB_FLYWAY_USERNAME}"
      FLYWAY_PASSWORD: "${ORDERS_DB_FLYWAY_PASSWORD}"
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092

networks:
  orders_system:
    driver: bridge
