
spring:
  datasource:
    url: ${DATABASE_BASE_URL}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: flyway
    user: ${FLYWAY_USER}
    password: ${FLYWAY_PASSWORD}

  # imports
  config:
    import: classpath:outbox-properties.yaml

server:
  port: 8080
  servlet:
    context-path: /api/v1
